# Generated by Django 3.1.4 on 2020-12-19 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_auto_20201217_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=datetime.date(2020, 12, 19)),
        ),
    ]
