# Generated by Django 3.1.4 on 2020-12-19 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_auto_20201219_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
